xx <- fread('FAOSTAT_data_5-27-2020.csv', colClasses = c('character',
                                                   'character',	
                                                   'character',
                                                   'character',
                                                   'character',
                                                   'character',
                                                   'character',
                                                   'character', 
                                                   'character',	
                                                   'character', 
                                                   'character',	
                                                   'character',	
                                                   'character',	
                                                   'numeric',	
                                                   'character', 
                                                   'character',	
                                                   'character'))
